// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ValidateSubscriptionPackagesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void validateSubscriptionPackages() {
    driver.get("https://subscribe.jawwy.tv//jo-en");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("jawwy-logo-web")));
    }
    driver.findElement(By.id("country-name")).click();
    driver.findElement(By.cssSelector("#eg-contry-flag > img")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("jawwy-logo-web")));
    }
    {
      List<WebElement> elements = driver.findElements(By.id("country-name"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".trial-cost")).getText(), is("From 20.00 Egyptian pound/week"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-lite"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-lite > b")).getText(), is("0.25"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-classic"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-classic > b")).getText(), is("0.5"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-premium"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-premium > b")).getText(), is("1"));
    driver.findElement(By.id("country-name")).click();
    driver.findElement(By.cssSelector("#ae-contry-flag > img")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("jawwy-logo-web")));
    }
    {
      List<WebElement> elements = driver.findElements(By.id("country-name"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".trial-cost")).getText(), is("From 10.00 AED/week"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-lite"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-lite > b")).getText(), is("5.4"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-classic"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-classic > b")).getText(), is("10.9"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-premium"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-premium > b")).getText(), is("16.3"));
    driver.findElement(By.id("country-name")).click();
    driver.findElement(By.cssSelector("#tn-contry-flag > img")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("jawwy-logo-web")));
    }
    {
      List<WebElement> elements = driver.findElements(By.id("country-name"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".trial-cost")).getText(), is("From 1.00 TND/week"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-lite"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-lite > b")).getText(), is("1.7"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-classic"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-classic > b")).getText(), is("3.4"));
    {
      List<WebElement> elements = driver.findElements(By.id("name-premium"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#currency-premium > b")).getText(), is("5.8"));
  }
}
